### ISSUE TITLE
Keep CHECK_INTERVAL consistent

### ISSUE THREAD

**Issue by maranik** [harsxv/tinystatus#13]
I’d like to suggest a small improvement: currently, using await asyncio.sleep(CHECK_INTERVAL) doesn’t take into account the time spent during the checks. A more accurate approach might be something like await asyncio.sleep(max(0, CHECK_INTERVAL - time_spent)) to compensate for that time.

PS: @harsxv, thank you very much for this amazing and straightforward project!

**Comment by harsxv** [comment]
Hmm that's make sense. Shoould be tested..
Thank you @maranik !
