### ISSUE TITLE
https://github.com/bderenzo/tinystatus

### ISSUE THREAD

**Issue by Redirts** [harsxv/tinystatus#14]
There seem to be at least 3 status page projects with the same name out there in Github :-)
I understand they have different features but I think it isn't a very good idea to have the same name.

https://github.com/bderenzo/tinystatus
https://github.com/theniwo/tinystatus (fork of one above)

Something to think about.

**Comment by harsxv** [comment]
Hmm, that's right. Definitely something to consider.
