### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by Aethelraed** [harsxv/tinystatus#15]
Awesome project,

please consider adding a [favicon.ico](https://github.com/user-attachments/files/16913691/favicon.zip) like the attached one.
Having a fine default favicon looks nice and is one less step to configure when hosting the generated html file.

![status-online-svgrepo-com_mod](https://github.com/user-attachments/assets/75575980-e108-44ec-8f70-e69203cce583)

**Comment by harsxv** [comment]
Hi, yes, this is already on the wishlist. Is this an original icon, and has it been used by anyone else before?

**Comment by Aethelraed** [comment]
I did place [the heartbeat](https://www.svgrepo.com/svg/440796/status-online) in white on a Hacker-News-orange square and believe it to be original. 

A quick [Google search](https://lens.google.com/search?ep=gisbubb&hl=en-DE&re=df&p=AbrfA8p8Lc0I3lrk2L4NPU3g5qGPyaTQEnLQ0cD9KCQ9ROqyI4ARjnD3dSRMfK7kPJhqRmVwToaPmdNInMJ_598OS0y4hX-TfaiJKZhT55Yy8VGSTY7B-x328a24JULLphrwypw-3i--1vlfpOpiNqaxVkUq1bhxIC1Us-Kspco4qbqyvkrGzTJqA1_qWvaFv3bA084wGPoyZJUX3w%3D%3D#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR1k0TmpBMU9UYzVMVFkwTm1ZdE5EY3pOaTFoTTJJMkxUTTRPR013TmpBMU5UVTVOaElmUVhreGIwTlFWSEpXZUUxa05FWXpjRVF5ZGpoaFkzTXRMVmcxUlVoU2F3PT0iLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsWyJlNjIyM2QzMS02MTBhLTQ0NDktYTlmMy0yMjZiMmQzZjQ0ZDgiXV0=) did find similar results, but no exact matches.

**Comment by harsxv** [comment]
Original logo and favicons is now UP! 

![android-chrome-384x384](https://github.com/user-attachments/assets/35432b4e-cbd8-4a64-8ed4-5afecf85b97a)
