### ISSUE TITLE
link on darkmode 

### ISSUE THREAD

**Issue by masdzub** [harsxv/tinystatus#26]
It seems like you’re facing an issue where links aren’t visible in dark mode because they blend into the background. 
To fix this, you can adjust the link’s color when in dark mode.

maybe i can fixing this issue, it just css issue.

![image](https://github.com/user-attachments/assets/996d1e91-91d3-4109-bdf8-713be3a2dfdd)

**Comment by harsxv** [comment]
Nice catch! I will assign the issue to you.

**Comment by harsxv** [comment]
This issue has been fixed on #28 - https://github.com/harsxv/tinystatus/pull/28/commits/171d5668aecef6d22e825b10ec7f89ec2ff9c4c5

Thanks @GeekyTim !

<img width="1290" alt="image" src="https://github.com/user-attachments/assets/47d55398-0389-4e2d-9d6f-afee7ad6b89b">
