### ISSUE TITLE
Local self-signed certs

### ISSUE THREAD

**Issue by GeekyTim** [harsxv/tinystatus#27]
Some of my internal servers use self-signed certificates, but I must monitor their interfaces. However, because they are self signed I get an error:

 Cannot connect to host xxxx.local ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)')]

Could this be handled differently (e.g. with a flag to ignore self-signed?)

**Comment by GeekyTim** [comment]
I have a solution, which I have implemented in my local version. Once I have tested it all out I will create a pull request.

**Comment by harsxv** [comment]
Since I dont have any self-signed certs, yet, I can't reproduce the issue. Looking forward for your PR! Thanks @GeekyTim

**Comment by GeekyTim** [comment]
Pull request requested.
