### ISSUE TITLE
Improve SEO Score - Pagespeed Web Dev

### ISSUE THREAD

**Issue by harsxv** [harsxv/tinystatus#30]
<img width="1018" alt="Screenshot 2024-10-03 at 15 26 28" src="https://github.com/user-attachments/assets/687aa3c9-8f2c-45f2-9503-8b81caf0eff1">
<img width="1003" alt="Screenshot 2024-10-03 at 15 26 24" src="https://github.com/user-attachments/assets/918e0da6-9e30-4135-9ac5-afac2679b8f9">

**Comment by aadir883** [comment]
Hi @harsxv , Can I work on this issue ? Please assign it to me

**Comment by harsxv** [comment]
Yes sure thing. Assigned to you

**Comment by AalokeCode** [comment]
@harsxv Can I work on this?

**Comment by harsxv** [comment]
Hey Aaloke! This looks like a similar case to your last PR. If we can make any improvements to boost the score, let’s go for it! But first, since this issue is assigned to @aadir883, let’s wait for their update. If we don't hear any news next day, feel free to jump in and take over.

**Comment by AalokeCode** [comment]
Alright!

**Comment by harsxv** [comment]
@AalokeCode whenever you're ready, feel free to take over the issue. Thanks!

**Comment by harsxv** [comment]
I will close this issue as it's already addressed in PR #40
