### ISSUE TITLE
Suggestion: Auto-refresh

### ISSUE THREAD

**Issue by GeekyTim** [harsxv/tinystatus#35]
Have a client-side autorefresh.

**Comment by harsxv** [comment]
Could you clarify what kind of auto refresh you're referring to? The script already has feature for continuous monitoring and automatically generates a new index.html.

**Comment by GeekyTim** [comment]
I didn't think mine was refreshing, so I added:

    <meta http-equiv="refresh" content="30">

My mistake - I see it in the .env.
