### ISSUE TITLE
Enhancement: Beautifying the Front-end side of things

### ISSUE THREAD

**Issue by AalokeCode** [harsxv/tinystatus#36]
Hey! I can help improving the current website by adding icons and small css tweaks. Please assign me this issue! Thanks in advance

**Comment by harsxv** [comment]
Hey @AalokeCode !

That's cool! Issue assigned to you.

Looking forward for the improvement :)

**Comment by AalokeCode** [comment]
Hey @harsxv, Please check PR #37

**Comment by harsxv** [comment]
Thanks, looking
