### ISSUE TITLE
Max Score on PageSpeed Insights

### ISSUE THREAD

**Issue by harsxv** [harsxv/tinystatus#8]
Hello!

I opened this `good first issue` to help first-time contributors get started.

The score on PageSpeed Insights can be improved to achieve a maximum score of 💯

Files can be checked:
- index.html.theme
- history.html.theme

It’s really just a matter of color contrast. I’ve adjusted it to pass the check here: https://dequeuniversity.com/rules/axe/4.9/color-contrast, but I’m not fond of the dark green against the background.

contrast analyzer | darker green result
--- | ---
<img width="486" alt="image" src="https://github.com/user-attachments/assets/97c6be57-47f1-4a23-8b73-114fcb568767"> | <img width="1245" alt="image" src="https://github.com/user-attachments/assets/e0ff16a0-356f-46ce-9c7d-b02078781fae">

Maybe someone with a stronger sense of UI/UX can help improve this. I’d appreciate your contribution!

Score currently: https://pagespeed.web.dev/analysis/https-status-harry-id/3bfccw1chu

<img width="1063" alt="Screenshot 2024-09-05 at 22 51 07" src="https://github.com/user-attachments/assets/abad7671-a0d6-4d96-8cdd-4fe617f9329a">

**Comment by Radbluelite** [comment]
Can I work on this issue to improve the accessiblity?

**Comment by harsxv** [comment]
Yes of course. I will assign the issue. Thank you!

**Comment by atinder-harika** [comment]
@harsxv Since there have been no pr's for this issue I would be glad to contribute, I have good experince with UI/UX in general.

**Comment by harsxv** [comment]
@atinder-harika sure, I've assigned to you. Thanks!

**Comment by atinder-harika** [comment]
#39 I have made pull request under this issue

**Comment by atinder-harika** [comment]
@harsxv I made PR #40, resolving this issue.
